const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'); const fs=require('node:fs');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true}); const ctx=await b.newContext({viewport:{width:390,height:844},acceptDownloads:true}); const p=await ctx.newPage(); const checks=[]; const errors=[]; p.on('pageerror',e=>errors.push(e.message)); const base=process.env.QA_URL||'http://localhost:3001';const pass=n=>{checks.push(n);console.log('PASS',n)};
async function login(page){await page.goto(base+'/login');await page.waitForLoadState('networkidle');await page.getByLabel('Access key').fill('q'.repeat(40));await page.getByRole('button',{name:'Meet your team'}).click();await page.waitForURL(base+'/');}
try {
 await p.goto(base+'/login'); await p.getByRole('link',{name:'Privacy & your data'}).click();await p.getByRole('heading',{name:'What Modeer stores about you'}).waitFor();await p.waitForLoadState('networkidle');assert.match(p.url(),/\/privacy$/);pass('privacy readable before login');
 await login(p); await p.goto(base+'/agents/study');await p.locator('textarea').fill('I live in Alexandria.');await p.getByRole('button',{name:'Send message',exact:true}).click();await p.getByText('offline preview response',{exact:false}).first().waitFor();await p.getByRole('button',{name:'Send message',exact:true}).waitFor();
 await p.getByRole('button',{name:/Conversation history/}).click();const del=p.getByRole('button',{name:/Delete conversation:/}).first();p.once('dialog',d=>d.dismiss());await del.click();assert.equal(await p.getByRole('button',{name:/Delete conversation:/}).count(),1);pass('conversation deletion can be cancelled');p.once('dialog',d=>d.accept());await del.click();await p.waitForFunction(()=>!document.querySelector('[aria-label^="Delete conversation:"]'));const convs=await (await p.request.get(base+'/api/conversations?agent_id=study')).json();assert.equal(convs.length,0);pass('conversation deletion removes transcript');
 await p.goto(base+'/');await p.request.get(base+'/api/briefings/today');await p.getByRole('link',{name:'Account',exact:true}).click();await p.getByRole('heading',{name:'You’re in control.'}).waitFor();
 const download=p.waitForEvent('download');await p.getByRole('button',{name:'Download my data'}).click();const file=await download;const data=JSON.parse(fs.readFileSync(await file.path(),'utf8'));assert(data.briefings.length>0);assert(data.shared_memories.some(m=>m.value==='Alexandria'));pass('account export with briefing downloads valid JSON');
 await p.route('**/api/users/me/export',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:'Please try downloading again.'})}));await p.getByRole('button',{name:'Download my data'}).click();await p.getByRole('alert').filter({hasText:'Please try downloading again.'}).waitFor();await p.unroute('**/api/users/me/export');pass('export failure is visible and recoverable');
 for(const width of [390,768,1440]){await p.setViewportSize({width,height:900});await p.goto(base+'/account');await p.waitForLoadState('networkidle');assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));if(width===390)await p.screenshot({path:process.env.QA_SCREENSHOT||'account-qa.png',fullPage:true});}pass('account fits mobile tablet and desktop');
 const other=await b.newContext();const p2=await other.newPage();await login(p2);await p.goto(base+'/account');p.once('dialog',d=>d.accept());await p.getByRole('button',{name:'Sign out every device'}).click();await p.waitForURL(base+'/login');assert.equal((await p2.request.get(base+'/api/users/me')).status(),401);pass('sign-out-everywhere revokes second browser session');await other.close();
 await login(p);await p.goto(base+'/account');const erase=p.getByRole('button',{name:'Permanently delete my account'});assert(await erase.isDisabled());await p.getByLabel('Type DELETE to confirm').fill('delete');assert(await erase.isDisabled());await p.getByLabel('Type DELETE to confirm').fill('DELETE');await erase.click();await p.waitForURL(base+'/login?deleted=1');assert.equal((await p.request.get(base+'/api/users/me')).status(),401);await p.getByLabel('Access key').fill('q'.repeat(40));await p.getByRole('button',{name:'Meet your team'}).click();await p.getByRole('alert').filter({hasText:'Invalid access key'}).waitFor();pass('account deletion requires exact confirmation and prevents re-login');
 assert.deepEqual(errors,[]);pass('no uncaught browser errors');fs.writeFileSync(process.env.QA_REPORT||'account-qa-results.json',JSON.stringify({provider:'mock',checks,errors},null,2));
} finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
